//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGenerator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3;2;3;47;16;17;18;19;20;13300;41;4;5;6;7;8;9;10;11;12;13;14;15;100;50;11064;55;")]
        public string OIPNumSettings {
            get {
                return ((string)(this["OIPNumSettings"]));
            }
            set {
                this["OIPNumSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8000;8096;9632;9760;9792;10112;10144;10400;9792;9792;")]
        public string TimerAdressSettings {
            get {
                return ((string)(this["TimerAdressSettings"]));
            }
            set {
                this["TimerAdressSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Станц Защ;Защ НА;Защ Рез;twList4;twNA;twCommTimes;twZDV;twVS;twASUPTzoneFoam;twAS" +
            "UPTzoneWater;")]
        public string TimerListSettings {
            get {
                return ((string)(this["TimerListSettings"]));
            }
            set {
                this["TimerListSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4;4;4;2;2;2;2;2;2;2;")]
        public string TimerStrSettings {
            get {
                return ((string)(this["TimerStrSettings"]));
            }
            set {
                this["TimerStrSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Gen_OIP_NoGap {
            get {
                return ((bool)(this["Gen_OIP_NoGap"]));
            }
            set {
                this["Gen_OIP_NoGap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int DB_version {
            get {
                return ((int)(this["DB_version"]));
            }
            set {
                this["DB_version"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DB_useRegSettings {
            get {
                return ((bool)(this["DB_useRegSettings"]));
            }
            set {
                this["DB_useRegSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DB_usePasswordCrypt {
            get {
                return ((bool)(this["DB_usePasswordCrypt"]));
            }
            set {
                this["DB_usePasswordCrypt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SQLOLEDB")]
        public string DB_Provider {
            get {
                return ((string)(this["DB_Provider"]));
            }
            set {
                this["DB_Provider"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost\\SQLEXPRESS")]
        public string DB_DataSource {
            get {
                return ((string)(this["DB_DataSource"]));
            }
            set {
                this["DB_DataSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OperMess")]
        public string DB_InitialCatalog {
            get {
                return ((string)(this["DB_InitialCatalog"]));
            }
            set {
                this["DB_InitialCatalog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sa")]
        public string DB_UserID {
            get {
                return ((string)(this["DB_UserID"]));
            }
            set {
                this["DB_UserID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sa")]
        public string DB_Password {
            get {
                return ((string)(this["DB_Password"]));
            }
            set {
                this["DB_Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public uint Gen_OIP_NoGapPlaceValue {
            get {
                return ((uint)(this["Gen_OIP_NoGapPlaceValue"]));
            }
            set {
                this["Gen_OIP_NoGapPlaceValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int startRow_ZDV {
            get {
                return ((int)(this["startRow_ZDV"]));
            }
            set {
                this["startRow_ZDV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int startRow_VS {
            get {
                return ((int)(this["startRow_VS"]));
            }
            set {
                this["startRow_VS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int startRow_StZash {
            get {
                return ((int)(this["startRow_StZash"]));
            }
            set {
                this["startRow_StZash"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int startRow_ZNA {
            get {
                return ((int)(this["startRow_ZNA"]));
            }
            set {
                this["startRow_ZNA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int Quntity_twCommTimes {
            get {
                return ((int)(this["Quntity_twCommTimes"]));
            }
            set {
                this["Quntity_twCommTimes"] = value;
            }
        }
    }
}
